
package lipid;

unit LipidScoreUnit;

// ===========================
// POSITIVE EVIDENCE
// ===========================

rule "1. RT increases with more carbon atoms (same type, same double bonds)"
when
    $a1 :/ annotations[
        $rt1 : getRtMin(),
        $carbonCount : getLipid().getCarbonCount(),
        $doubleBoundCount : getLipid().getDoubleBondsCount(),
        $type : getLipid().getLipidType()
    ]
    $a2 : /annotations[
        this != $a1,
        getLipid().getLipidType() == $type,
        getLipid().getDoubleBondsCount() == $doubleBoundCount,
        getLipid().getCarbonCount() > $carbonCount,
        getRtMin() > $rt1
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
end

rule "2. RT increases with fewer double bonds (same type, same carbon count)"
when
    $a1 : /annotations[
        $rt1 : getRtMin(),
        $doubleBoundCount : getLipid().getDoubleBondsCount(),
        $carbonCount : getLipid().getCarbonCount(),
        $type : getLipid().getLipidType()
    ]
    $a2 :/ annotations[
        this != $a1,
        getLipid().getLipidType() == $type,
        getLipid().getCarbonCount() == $carbonCount,
        getLipid().getDoubleBondsCount() <  $doubleBoundCount,
        getRtMin() > $rt1
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
end

rule "3. RT increases with higher lipid type priority (same double bonds and carbons)"
when
    $a1 : /annotations[
        $rt1 : getRtMin(),
        $doubleBoundCount : getLipid().getDoubleBondsCount(),
        $carbonCount : getLipid().getCarbonCount(),
        $type : getLipid().getLipidType()
    ]
    $a2 : /annotations[
        this != $a1,
        getLipid().getDoubleBondsCount() == $doubleBoundCount,
        getLipid().getCarbonCount() ==$carbonCount ,
        getLipid().getLipidType() != $type,
        Lipid.getPriority(getLipid().getLipidType()) > Lipid.getPriority($type),
        getRtMin() > $rt1
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
end


// ===========================
// NEGATIVE EVIDENCE
// ===========================

rule "4. RT decreases with more carbon atoms "
when
    $a1 :/ annotations[
        $rt1 : getRtMin(),
        $carbonCount : getLipid().getCarbonCount(),
        $doubleBoundCount : getLipid().getDoubleBondsCount(),
        $type : getLipid().getLipidType()
    ]
    $a2 : /annotations[
        this != $a1,
        getLipid().getLipidType() == $type,
        getLipid().getDoubleBondsCount() ==  $doubleBoundCount,
        getLipid().getCarbonCount() > $carbonCount,
        getRtMin() < $rt1
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
end

rule "5. RT decreases with fewer double bonds "
when
    $a1 : /annotations[
        $rt1 : getRtMin(),
        $doubleBoundCount : getLipid().getDoubleBondsCount(),
        $carbonCount : getLipid().getCarbonCount(),
        $type : getLipid().getLipidType()
    ]
    $a2 : /annotations[
        this != $a1,
        getLipid().getLipidType() == $type,
        getLipid().getCarbonCount() == $carbonCount,
        getLipid().getDoubleBondsCount() <  $doubleBoundCount,
        getRtMin() < $rt1
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
end

rule "6. RT decreases with later eluting lipid type"
when
    $a1 : /annotations[
        $rt1 : getRtMin(),
        $doubleBoundCount : getLipid().getDoubleBondsCount(),
        $carbonCount : getLipid().getCarbonCount(),
        $type : getLipid().getLipidType()
    ]
    $a2 : /annotations[
        this != $a1,
        getLipid().getDoubleBondsCount() == $doubleBoundCount,
        getLipid().getCarbonCount() == $carbonCount,
        getLipid().getLipidType() != $type,
        Lipid.getPriority(getLipid().getLipidType()) > Lipid.getPriority($type),
        getRtMin() < $rt1
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
end